# -*- mode: ruby -*-
# vi: set ft=ruby :

nodes = [
  { :name => "db-lab",  :ip => "192.168.33.10" },
  { :name => "web-lab", :ip => "192.168.33.11" },
]

Vagrant.configure("2") do |config|
  nodes.each do |node|
    config.vm.define node[:name] do |nconf|
      nconf.vm.box = "nixbox/nixos"
      nconf.vm.box_version = "23.05" # 23.11 hangs; https://github.com/NixOS/nixpkgs/issues/262686
      nconf.vm.box_check_update = false

      nconf.vm.hostname = node[:name]
      nconf.vm.network "private_network", type: "static", ip: node[:ip]
      nconf.vm.synced_folder ".", "/vagrant", disabled: true

      nconf.vm.provision "shell" do |s|
        ssh_pub_key = File.readlines("#{ENV['HOME']}/.ssh/id_ed25519.pub").first.strip
        s.inline = <<-SHELL
          mkdir --mode=0700 /root/.ssh
          echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
        SHELL
      end

      # Activate hostname, network config.
      nconf.vm.provision "shell", inline: "nixos-rebuild boot 2>&1 | tee /tmp/build.log", reboot: true

      nconf.vm.provider "libvirt" do |libvirt|
        libvirt.driver = "kvm"
        libvirt.cpus = 2
        libvirt.cputopology :sockets => '1', :cores => '2', :threads => '1'
        libvirt.memory = 1024 # nixos-rebuild silently fails with 512
      end
    end
  end
end
